version: '3.9'
services:
  postgres_final:
    image: postgres:14.1-alpine
    container_name: postgres_final
    restart: on-failure
    ports:
      - "5433:5432" #puertoLocal : puertoContenedor
    volumes:
      - ./temp/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nodejs_course
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nodejs_course_password
